
od_list = ['1000  Device Type',
           '1001  Error Register',
           '1002  Manufaturer Status Register',
           '1003  Predefined Error Field',
           '1005  COBID SYNC',
           '1006  Communication Cycle Period',
           '1007  Synchronous Window Length',
           '1008  Manufacturer Device Name',
           '1009  Manufacturer Hardware Version',
           '100A  Manufacturer Software Version',
           '100C  Guard Time',
           '100D  Life Time Factor',
           '1010  Store Parameter Field',
           '1011  Restore Default Parameters',
           '1012  COBID TimeStamp',
           '1013  High Resolution Time Stamp1',
           '1014  COBID EMCY',
           '1015  Inhibit Time Emergency',
           '1016  Consumer Hear Beat Time',
           '1017  Producer Heartbeat Time',
           '1018  Identity Object',
           '1019  Synchronous Counter Overflow Value',
           '1020  Verify Configuration',
           '1021  Store EDS',
           '1022  Storage Format',
           '1023  OS Command',
           '1024  OS Command Module',
           '1025  OS Debug',
           '1026  OS Prompt',
           '1027  Module List',
           '1028  Emergency Consumer',
           '1029  Eror Behaviour',
           '1200  Server SDO Parameter 0',
           '1201  Server SDO Parameter 1',
           '1201  Server SDO Parameter 2',
           '1203  Server SDO Parameter 3',
           '1204  Server SDO Parameter 4',
           '1400  Receive PDO Communication Parameter 0',
           '1401  Receive PDO Communication Parameter 1',
           '1402  Receive PDO Communication Parameter 2',
           '1403  Receive PDO Communication Parameter 3',
           '1404  Receive PDO Communication Parameter 4',
           '1405  Receive PDO Communication Parameter 5',
           '1406  Receive PDO Communication Parameter 6',
           '1407  Receive PDO Communication Parameter 7',
           '1408  Receive PDO Communication Parameter 8',
           '1409  Receive PDO Communication Parameter 9',
           '140A  Receive PDO Communication Parameter 10',
           '140B  Receive PDO Communication Parameter 11',
           '140C  Receive PDO Communication Parameter 12',
           '140D  Receive PDO Communication Parameter 13',
           '140E  Receive PDO Communication Parameter 14',
           '1600  Receive PDO Mapping Parameter 0',
           '1601  Receive PDO Mapping Parameter 1',
           '1602  Receive PDO Mapping Parameter 2',
           '1603  Receive PDO Mapping Parameter 3',
           '1604  Receive PDO Mapping Parameter 4',
           '1605  Receive PDO Mapping Parameter 5',
           '1606  Receive PDO Mapping Parameter 6',
           '1607  Receive PDO Mapping Parameter 7',
           '1608  Receive PDO Mapping Parameter 8',
           '1609  Receive PDO Mapping Parameter 9',
           '160A  Receive PDO Mapping Parameter 10',
           '160B  Receive PDO Mapping Parameter 11',
           '160C  Receive PDO Mapping Parameter 12',
           '160D  Receive PDO Mapping Parameter 13',
           '160E  Receive PDO Mapping Parameter 14',
           '1800  Transmit PDO Communication Parameter 0',
           '1801  Transmit PDO Communication Parameter 1',
           '1802  Transmit PDO Communication Parameter 2',
           '1803  Transmit PDO Communication Parameter 3',
           '1804  Transmit PDO Communication Parameter 4',
           '1805  Transmit PDO Communication Parameter 5',
           '1806  Transmit PDO Communication Parameter 6',
           '1807  Transmit PDO Communication Parameter 7',
           '1808  Transmit PDO Communication Parameter 8',
           '1809  Transmit PDO Communication Parameter 9',
           '180A  Transmit PDO Communication Parameter 10',
           '180B  Transmit PDO Communication Parameter 11',
           '180C  Transmit PDO Communication Parameter 12',
           '180D  Transmit PDO Communication Parameter 13',
           '180E  Transmit PDO Communication Parameter 14',
           '1A00  Transmit PDO  Mapping Parameter 0',
           '1A01  Transmit PDO  Mapping Parameter 1',
           '1A02  Transmit PDO  Mapping Parameter 2',
           '1A03  Transmit PDO  Mapping Parameter 3',
           '1A04  Transmit PDO  Mapping Parameter 4',
           '1A05  Transmit PDO  Mapping Parameter 5',
           '1A06  Transmit PDO  Mapping Parameter 6',
           '1A07  Transmit PDO  Mapping Parameter 7',
           '1A08  Transmit PDO  Mapping Parameter 8',
           '1A09  Transmit PDO  Mapping Parameter 9',
           '1A0A  Transmit PDO  Mapping Parameter 10',
           '1A0B  Transmit PDO  Mapping Parameter 11',
           '1A0C  Transmit PDO  Mapping Parameter 12',
           '1A0D  Transmit PDO  Mapping Parameter 13',
           '1A0E  Transmit PDO  Mapping Parameter 14'
           '6000  ReadInput 8 Bit',
           '6002  Polarity Input 8 Bit',
           '6003  Filter Constant Input 8 Bit',
           '6005  Global Interrput Enable Digital 8 Bit',
           '6006  Interrupt Mak Any Change 8 Bit',
           '6007  Interrupt Mask Low to High 8 Bit',
           '6008  Interrput Mask High to Low 8 Bit',
           '6020  Read Input 1 Bit',
           '6021  Read Input 1 Bit',
           '6022  Read Input 1 Bit',
           '6023  Read Input 1 Bit',
           '6024  Read Input 1 Bit',
           '6025  Read Input 1 Bit',
           '6026  Read Input 1 Bit',
           '6027  Read Input 1 Bit',
           '6030  Polarity Input 1 Bit',
           '6031  Polarity Input 1 Bit',
           '6032  Polarity Input 1 Bit',
           '6033  Polarity Input 1 Bit',
           '6034  Polarity Input 1 Bit',
           '6035  Polarity Input 1 Bit',
           '6036  Polarity Input 1 Bit',
           '6037  Polarity Input 1 Bit',
           '6038  Filter Constant Input Bit 1 Bit',
           '6039  Filter Constant Input Bit 1 Bit',
           '603A  Filter Constant Input Bit 1 Bit',
           '603B  Filter Constant Input Bit 1 Bit',
           '603C  Filter Constant Input Bit 1 Bit',
           '603D  Filter Constant Input Bit 1 Bit',
           '603E  Filter Constant Input Bit 1 Bit',
           '603F  Filter Constant Input Bit 1 Bit',
           '6050  Interrupt Mask Input Bit Any Change 1 Bit',
           '6051  Interrupt Mask Input Bit Any Change 1 Bit',
           '6052  Interrupt Mask Input Bit Any Change 1 Bit',
           '6053  Interrupt Mask Input Bit Any Change 1 Bit',
           '6054  Interrupt Mask Input Bit Any Change 1 Bit',
           '6055  Interrupt Mask Input Bit Any Change 1 Bit',
           '6056  Interrupt Mask Input Bit Any Change 1 Bit',
           '6057  Interrupt Mask Input Bit Any Change 1 Bit',
           '6060  Interrupt Mask Input Low to High 1 Bit',
           '6061  Interrupt Mask Input Low to High 1 Bit',
           '6062  Interrupt Mask Input Low to High 1 Bit',
           '6063  Interrupt Mask Input Low to High 1 Bit',
           '6064  Interrupt Mask Input Low to High 1 Bit',
           '6065  Interrupt Mask Input Low to High 1 Bit',
           '6066  Interrupt Mask Input Low to High 1 Bit',
           '6067  Interrupt Mask Input Low to High 1 Bit',
           '6070  Interrupt Mask Input High to Low 1 Bit',
           '6071  Interrupt Mask Input High to Low 1 Bit',
           '6072  Interrupt Mask Input High to Low 1 Bit',
           '6073  Interrupt Mask Input High to Low 1 Bit',
           '6074  Interrupt Mask Input High to Low 1 Bit',
           '6075  Interrupt Mask Input High to Low 1 Bit',
           '6076  Interrupt Mask Input High to Low 1 Bit',
           '6077  Interrupt Mask Input High to Low 1 Bit',
           '6100  Read Input 16 Bit',
           '6102  Polarity Input 16 Bit',
           '6103  Filter Constant Input 16 Bit',
           '6106  Interrupt Mask Any Change 16 Bit',
           '6107  Interrupt Mask Low to High 16 Bit',
           '6108  Interrupt Mask High to Low 16 Bit',
           '6120  Read Input 32 Bit',
           '6122  Polarity Input 32 Bit',
           '6123  Filter Constant Input 32 Bit',
           '6126  Interrupt Mask Input Bit Any Change 32 Bit',
           '6127  Interrupt Mask Input Low to High 32 Bit',
           '6128  Interrupt Mask Input High to Low 32 Bit',
           '6200  Write Output 8 Bit',
           '6202  Polarity Output 8 Bit',
           '6206  Error Mode Output 8 Bit',
           '6207  Error Value Output 8 Bit',
           '6208  Filter Mask Output 8 Bit',
           '6220  Write Output 1 Bit',
           '6221  Write Output 1 Bit',
           '6222  Write Output 1 Bit',
           '6223  Write Output 1 Bit',
           '6224  Write Output 1 Bit',
           '6225  Write Output 1 Bit',
           '6226  Write Output 1 Bit',
           '6227  Write Output 1 Bit',
           '6240  Polarity Output 1 Bit',
           '6241  Polarity Output 1 Bit',
           '6242  Polarity Output 1 Bit',
           '6243  Polarity Output 1 Bit',
           '6244  Polarity Output 1 Bit',
           '6245  Polarity Output 1 Bit',
           '6246  Polarity Output 1 Bit',
           '6247  Polarity Output 1 Bit',
           '6250  Error Mode Output 1 Bit',
           '6251  Error Mode Output 1 Bit',
           '6252  Error Mode Output 1 Bit',
           '6253  Error Mode Output 1 Bit',
           '6254  Error Mode Output 1 Bit',
           '6255  Error Mode Output 1 Bit',
           '6256  Error Mode Output 1 Bit',
           '6257  Error Mode Output 1 Bit',
           '6260  Error Value Output 1 Bit',
           '6261  Error Value Output 1 Bit',
           '6262  Error Value Output 1 Bit',
           '6263  Error Value Output 1 Bit',
           '6264  Error Value Output 1 Bit',
           '6265  Error Value Output 1 Bit',
           '6266  Error Value Output 1 Bit',
           '6267  Error Value Output 1 Bit',
           '6270  Filter Mask Output 1 Bit',
           '6271  Filter Mask Output 1 Bit',
           '6272  Filter Mask Output 1 Bit',
           '6273  Filter Mask Output 1 Bit',
           '6274  Filter Mask Output 1 Bit',
           '6275  Filter Mask Output 1 Bit',
           '6276  Filter Mask Output 1 Bit',
           '6277  Filter Mask Output 1 Bit',
           '6300  Write Output 16 Bit',
           '6302  Polarity Output 16 Bit',
           '6306  Error Mode Output 16 Bit',
           '6307  Error value Output 16 Bit',
           '6308  Filter Mak Output 16 Bit',
           '6320  Write Output 32 Bit',
           '6322  POlarity Output 32 Bit',
           '6326  Error Mode Output 32 Bit',
           '6327  Error Value Output 32 Bit',
           '6328  Filter Mask Output 32 Bit',
           '6400  Read Analogue Input 8 Bit',
           '6401  Read Analogue Input 16 Bit',
           '6402  Read Analogue Input 32 Bit',
           '6403  Read Analogue Input Float',
           '6404  Read Manufacture Specific Analogue Input',
           '6410  Write Analogue Output 8 Bit',
           '6411  Write Analogue Output 16 Bit',
           '6412  Write Analogue Output 32 Bit',
           '6413  Write Analogue Output Float'
           '6414  Write Manufacturer Specific Analogue Output',
           '6421  Interrupt Trigger Selection',
           '6422  Analogue Input Interrupt Source',
           '6423  Analogue Input Global Interrupt Enable',
           '6424  Analogue Input Interrupt Upper Limit Integer',
           '6425  Analogue Input Interrupt Lower Limit Integer',
           '6426  Analogue Input Interrupt Delta Unsigned',
           '6427  Analogue Input Interrupt Negative Delta Unsigned',
           '6428  Analogue Input Interrupt Positive Delta Unsigned',
           '6429  Analogue Input Interrupt Upper Limit Float',
           '642A  Analogue Input Interrupt Lower Limit Float',
           '642B  Analogue Input Interrupt Delta Float',
           '642C  Analogue Input Interrupt Negative Delta Float',
           '642D  Analogue Input Interrupt Positive Delta Float',
           '642E  Analogue Input Offset Float',
           '642F  Analogue Input Scaling Float',
           '6430  Analogue Input SI Unit',
           '6431  Analogue Input Offset Integer',
           '6432  Analogue Input Scaling Integer',
           '6441  Analogue Output Offset Float',
           '6442  Analogue Output Scaling Float',
           '6443  Analogue Output Error Mode',
           '6444  Analogue Output Error Value Integer'
           '6445  Analogue Output Error Value Float',
           '6446  Analogue Output Offset Integer',
           '6447  Analogue Output Scaling Integer',
           '6450  Analogue Output SI Unit'
                      ]
