#ifndef OBJECT_DICTIONARY_H_
#define OBJECT_DICTIONARY_H_

/*
 * This file is magically generated by the object dictionary genarator
 */

#define NUMBER_OF_OBJECTS 10
#define NUMBER_OF_SUBINDEX_POINTERS 100
#define NUMBER_OF_DATA_BYTES 1000

unsigned char data[NUMBER_OF_DATA_BYTES]; // = {load of data};
void * subindex_pointers[NUMBER_OF_SUBINDEX_POINTERS]; // = {loads of pointers into the above data};
object object_dict[NUMBER_OF_OBJECTS]; // = {loads of objects with subindex pointers into the above};

//I'll explain this tomorrow!
#define read_UNSIGNED16_0x1000_0 return (data, UNSIGNED16[])[3];
#define read_UNSIGNED8_0x1004_0 return (data, UNSIGNED8[])[7];

#define write_UNSIGNED16_0x1000_0(x) (data, UNSIGNED16[])[3] = x;
#define write_UNSIGNED8_0x1004_0(x) (data, UNSIGNED8[])[7] = x;

#endif /* OBJECT_DICTIONARY_H_ */
